kafka:
  fullnameOverride: kafka
  controller:
    replicaCount: 1

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    persistence:
      enabled: true
      size: 5Gi

    logPersistence:
      enabled: false

    pdb:
      create: false

    affinity: {}

  overrideConfiguration:
    log.retention.hours: 24
    log.retention.bytes: 536870912
    offsets.topic.replication.factor: 1
    transaction.state.log.replication.factor: 1
    min.insync.replicas: 1
    default.replication.factor: 1
    auto.create.topics.enable: true
    num.partitions: 1

kafka-ui:
  fullnameOverride: kafka-ui
  replicaCount: 1

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  ingress:
    enabled: false

  yamlApplicationConfig:
    kafka:
      clusters:
        - name: popcorn-kafka-dev
          bootstrapServers: kafka:9092
          readOnly: false

  env:
    - name: KAFKA_CLUSTERS_0_NAME
      value: "popcorn-kafka-dev"
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: "kafka:9092"
