apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  SERVER_PORT: "8085"
  FRONTEND_BASE_URL: "https://goormpopcorn.shop"
  DB_HOST: "goorm-popcorn-prod-postgres.cds4g0gykt3t.ap-northeast-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "popcorn_prod"
  REDIS_HOST: "master.goorm-popcorn-cache-prod.mkltth.apn2.cache.amazonaws.com"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-prod.kafka.svc.cluster.local:9092"
  GATEWAY_URL: "https://api.goormpopcorn.shop"
  ORDER_SERVICE_BASE_URL: "http://popcorn-prod-gateway:8080"
  USER_SERVICE_BASE_URL: "http://popcorn-prod-gateway:8080"
  PAYMENT_WEBHOOK_TIMEOUT: "15000"
  PAYMENT_MAX_AMOUNT: "1000000"
  PAYMENT_NOTIFICATION_ENABLED: "true"
  PAYMENT_NOTIFICATION_RETRY: "5"
  PAYMENT_ORDER_QUERY_TIMEOUT: "5000"
  TOSS_PAYMENTS_BASE_URL: "https://api.tosspayments.com"
  TOSS_PAYMENTS_TEST_MODE: "false"
