apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  DB_HOST: "goorm-popcorn-prod-postgres.cds4g0gykt3t.ap-northeast-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "popcorn_prod"
  REDIS_HOST: "master.goorm-popcorn-cache-prod.mkltth.apn2.cache.amazonaws.com"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-prod.kafka.svc.cluster.local:9092"
  FRONTEND_BASE_URL: "https://dev.goormpopcorn.shop"
  USER_SERVICE_BASE_URL: "http://popcorn-prod-gateway:8080/"
  STORE_SERVICE_BASE_URL: "http://popcorn-prod-gateway:8080/"
  ORDERQUERY_SERVICE_BASE_URL: "http://popcorn-prod-gateway:8080/"
  ORDER_PAYMENT_TIMEOUT: "15000"
  ORDER_CANCEL_TIMEOUT: "900"
  ORDER_RESERVATION_WAIT_TIMEOUT_MS: "0"
  ORDER_MAX_QUANTITY: "50"
  ORDER_MIN_QUANTITY: "1"
  ORDER_NOTIFICATION_ENABLED: "true"
  ORDER_NOTIFICATION_RETRY: "5"
  ORDER_ORDERQUERY_TIMEOUT: "3000"
