apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-connect.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-connect.name" . }}
    helm.sh/chart: {{ include "kafka-connect.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: kafka-connect
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka-connect.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kafka-connect.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
{{ toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: kafka-connect
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers | quote }}
            - name: GROUP_ID
              value: {{ .Values.connect.groupId | quote }}
            - name: CONFIG_STORAGE_TOPIC
              value: {{ .Values.connect.configStorageTopic | quote }}
            - name: OFFSET_STORAGE_TOPIC
              value: {{ .Values.connect.offsetStorageTopic | quote }}
            - name: STATUS_STORAGE_TOPIC
              value: {{ .Values.connect.statusStorageTopic | quote }}
            - name: CONFIG_STORAGE_REPLICATION_FACTOR
              value: {{ .Values.connect.configStorageReplicationFactor | quote }}
            - name: OFFSET_STORAGE_REPLICATION_FACTOR
              value: {{ .Values.connect.offsetStorageReplicationFactor | quote }}
            - name: STATUS_STORAGE_REPLICATION_FACTOR
              value: {{ .Values.connect.statusStorageReplicationFactor | quote }}
            - name: KEY_CONVERTER
              value: {{ .Values.converters.keyConverter | quote }}
            - name: VALUE_CONVERTER
              value: {{ .Values.converters.valueConverter | quote }}
            - name: VALUE_CONVERTER_SCHEMAS_ENABLE
              value: {{ .Values.converters.valueConverterSchemasEnable | quote }}
            - name: REST_ADVERTISED_HOST_NAME
              value: {{ include "kafka-connect.fullname" . }}
            - name: REST_PORT
              value: {{ .Values.service.port | quote }}
{{- range .Values.pod.extraEnv }}
{{- toYaml . | nindent 12 }}
{{- end }}
          readinessProbe:
{{- if .Values.pod.probes.enabled }}
            httpGet:
              path: /connectors
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.pod.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.pod.probes.periodSeconds }}
{{- else }}
            exec:
              command: ["/bin/sh", "-c", "exit 0"]
{{- end }}
          livenessProbe:
{{- if .Values.pod.probes.enabled }}
            httpGet:
              path: /connectors
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
{{- else }}
            exec:
              command: ["/bin/sh", "-c", "exit 0"]
{{- end }}
          resources:
{{ toYaml .Values.pod.resources | nindent 12 }}
      topologySpreadConstraints: {{- toYaml .Values.pod.topologySpreadConstraints | nindent 8 }}
{{- if .Values.pod.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.pod.nodeSelector | nindent 8 }}
{{- end }}
{{- if .Values.pod.tolerations }}
      tolerations:
{{ toYaml .Values.pod.tolerations | nindent 8 }}
{{- end }}
{{- if .Values.pod.affinity }}
      affinity:
{{ toYaml .Values.pod.affinity | nindent 8 }}
{{- end }}
      restartPolicy: Always
