apiVersion: v2
name: gateway
description: Popcorn API Gateway service (Spring Cloud Gateway)
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
- name: common
  version: "1.0.0"
  repository: "helm/popcorn-umbrella/charts/common"
