apiVersion: v2
name: order-query
description: Popcorn Order Query Service (CQRS Query)
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
- name: common
  version: "1.0.0"
  repository: "file://../common"
