apiVersion: v2
name: frontend
description: Popcorn Frontend (Next.js)
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
- name: common
  version: "1.0.0"
  repository: "file://../common"
