replicaCount: 1

image:
  repository: 375896310755.dkr.ecr.ap-northeast-2.amazonaws.com/goorm-popcorn-payment
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080

env:
  SPRING_PROFILES_ACTIVE: "default"
  SERVER_PORT: "8080"
  JAVA_OPTS: "-Xms256m -Xmx512m"

envFrom:
  - configMapRef:
      name: "{{ .Release.Name }}-payment-config"
      optional: true
  - secretRef:
      name: rds-credentials
      optional: true
  - secretRef:
      name: redis-credentials
      optional: true
  - secretRef:
      name: database-users
      optional: true
  - secretRef:
      name: payment-api-keys
      optional: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

healthCheck:
  enabled: true
  path: /actuator/health
  livenessPath: /actuator/health/liveness
  readinessPath: /actuator/health/readiness
  initialDelaySeconds: 60
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
