apiVersion: v2
name: popcorn-umbrella
description: Popcorn MSA Application Umbrella Chart
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
- name: frontend
  version: "1.0.0"
  repository: "file://../charts/frontend"
  condition: frontend.enabled

- name: gateway
  version: "1.0.0"
  repository: "file://../charts/gateway"
  condition: gateway.enabled

- name: users
  version: "1.0.0"
  repository: "file://../charts/users"
  condition: users.enabled

- name: stores
  version: "1.0.0"
  repository: "file://../charts/stores"
  condition: stores.enabled

- name: order
  version: "1.0.0"
  repository: "file://../charts/order"
  condition: order.enabled

- name: payment
  version: "1.0.0"
  repository: "file://../charts/payment"
  condition: payment.enabled

- name: order-query
  version: "1.0.0"
  repository: "file://../charts/order-query"
  condition: order-query.enabled

- name: checkins
  version: "1.0.0"
  repository: "file://../charts/checkins"
  condition: checkins.enabled

- name: coupon
  version: "1.0.0"
  repository: "file://../charts/coupon"
  condition: coupon.enabled

- name: common
  version: "1.0.0"
  repository: "file://../charts/common"
